#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# yarn lint-staged

echo '🏗👷🏼 Styling, testing and building your code before committing.'

yarn check-types ||
(
  echo '🙈 Failed type checking, please fix the errors above and try again.'
  false;
)





echo '✅ Codes looking good...running build'

yarn build ||
(
  echo '🃏 Looks like your build failed, please fix the errors above and try again.'
  false;
)

echo '🎉 Build complete, committing now...'